name: API CI

on:
  push:
    branches: [ main ]
    paths:
      - 'python-backend/**'
  pull_request:
    paths:
      - 'python-backend/**'
  workflow_dispatch: {}

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: python-backend
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: python -m pip install --upgrade pip
      - run: pip install -r requirements.txt
      - name: Import smoke test
        run: |
          python - <<'PY'
          import importlib
          for mod in ['fastapi','httpx','motor','dotenv']:
              importlib.import_module(mod)
          print('Imports OK')
          PY
      - name: Run pytest
        env:
          # Provide safe defaults for envs referenced in app
          MONGODB_URI: ""
          MONGODB_DB: "testdb"
          NUTRITIONIX_APP_ID: "dummy"
          NUTRITIONIX_API_KEY: "dummy"
        run: pytest -q
